@startmindmap
* アプリ
** サービス
*** ユーザーサービス
note left: ユーザーとのインタラクションに関連する\n機能や機能グループを提供する\nサービス
*** データサービス
note left: データの取得、保存、処理、管理などを\n担当するサービス
*** 通信サービス
note left: ネットワークとの通信に関連する\n機能やプロトコルを提供する\nサービス
** ツール
*** 開発ツール
note left: ソフトウェア開発に使用される\nツールや環境
**** 統合開発環境（IDE）
note left: コーディング、デバッグ、ビルド、テストなどの\n開発タスクを統合した環境を提供する\nツール
**** デバッグツール
note left: プログラムの実行中にバグを特定し\n修正するためのツール
**** パフォーマンス解析ツール
note left: アプリケーションのパフォーマンスを\n測定、分析するためのツール
*** デザインツール
note left: グラフィックデザインやUI/UXデザインに\n使用されるツール
**** グラフィックデザインツール
note left: イメージ編集、イラスト作成、\nレイアウト設計などをサポートするツール
**** UI/UXデザインツール
note left: ユーザーインターフェース（UI）\nおよびユーザーエクスペリエンス（UX）\nの設計を支援するツール
**** プロトタイピングツール
note left: アプリケーションのプロトタイプ作成や\nユーザーテストに使用されるツール
** 製品
*** ハードウェア製品
note left: 物理的な機器やデバイスを指す\nコンピュータ、スマートフォン、\nタブレットなど
**** コンピュータ
note left: ソフトウェアの実行や情報処理を\n行う電子デバイス
**** スマートフォン
note left: モバイル通信機能を持つ電子デバイス
@endmindmap